/**
 * KryptoPal Wallet API
 * This is the API specification for KryptoPal
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dev@KryptoPal.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Crypto {
  
  @SerializedName("rows")
  private List<Object> rows = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<Object> getRows() {
    return rows;
  }
  public void setRows(List<Object> rows) {
    this.rows = rows;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Crypto crypto = (Crypto) o;
    return (this.rows == null ? crypto.rows == null : this.rows.equals(crypto.rows));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.rows == null ? 0: this.rows.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Crypto {\n");
    
    sb.append("  rows: ").append(rows).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
