/**
 * KryptoPal Wallet API
 * This is the API specification for KryptoPal
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dev@KryptoPal.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A User who is purchasing from the pet store
 **/
@ApiModel(description = "A User who is purchasing from the pet store")
public class User {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("username")
  private String username = null;
  @SerializedName("firstName")
  private String firstName = null;
  @SerializedName("lastName")
  private String lastName = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("password")
  private String password = null;
  @SerializedName("phoneNumber")
  private Integer phoneNumber = null;
  @SerializedName("userStatus")
  private Integer userStatus = null;
  @SerializedName("memberships")
  private String memberships = null;
  @SerializedName("ethAddress")
  private String ethAddress = null;
  @SerializedName("btcAddress")
  private String btcAddress = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPhoneNumber() {
    return phoneNumber;
  }
  public void setPhoneNumber(Integer phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  /**
   * User Status
   **/
  @ApiModelProperty(value = "User Status")
  public Integer getUserStatus() {
    return userStatus;
  }
  public void setUserStatus(Integer userStatus) {
    this.userStatus = userStatus;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMemberships() {
    return memberships;
  }
  public void setMemberships(String memberships) {
    this.memberships = memberships;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEthAddress() {
    return ethAddress;
  }
  public void setEthAddress(String ethAddress) {
    this.ethAddress = ethAddress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBtcAddress() {
    return btcAddress;
  }
  public void setBtcAddress(String btcAddress) {
    this.btcAddress = btcAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return (this.id == null ? user.id == null : this.id.equals(user.id)) &&
        (this.username == null ? user.username == null : this.username.equals(user.username)) &&
        (this.firstName == null ? user.firstName == null : this.firstName.equals(user.firstName)) &&
        (this.lastName == null ? user.lastName == null : this.lastName.equals(user.lastName)) &&
        (this.email == null ? user.email == null : this.email.equals(user.email)) &&
        (this.password == null ? user.password == null : this.password.equals(user.password)) &&
        (this.phoneNumber == null ? user.phoneNumber == null : this.phoneNumber.equals(user.phoneNumber)) &&
        (this.userStatus == null ? user.userStatus == null : this.userStatus.equals(user.userStatus)) &&
        (this.memberships == null ? user.memberships == null : this.memberships.equals(user.memberships)) &&
        (this.ethAddress == null ? user.ethAddress == null : this.ethAddress.equals(user.ethAddress)) &&
        (this.btcAddress == null ? user.btcAddress == null : this.btcAddress.equals(user.btcAddress));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.username == null ? 0: this.username.hashCode());
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.password == null ? 0: this.password.hashCode());
    result = 31 * result + (this.phoneNumber == null ? 0: this.phoneNumber.hashCode());
    result = 31 * result + (this.userStatus == null ? 0: this.userStatus.hashCode());
    result = 31 * result + (this.memberships == null ? 0: this.memberships.hashCode());
    result = 31 * result + (this.ethAddress == null ? 0: this.ethAddress.hashCode());
    result = 31 * result + (this.btcAddress == null ? 0: this.btcAddress.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  username: ").append(username).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  password: ").append(password).append("\n");
    sb.append("  phoneNumber: ").append(phoneNumber).append("\n");
    sb.append("  userStatus: ").append(userStatus).append("\n");
    sb.append("  memberships: ").append(memberships).append("\n");
    sb.append("  ethAddress: ").append(ethAddress).append("\n");
    sb.append("  btcAddress: ").append(btcAddress).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
